spring.application.name=voiceout
spring.datasource.url=jdbc:postgresql://localhost:5432/voiceout
spring.datasource.username=postgres
spring.datasource.password=kolli
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=${SERVER_PORT:8080}

voiceout.frontend-origin=http://localhost:5173
voiceout.admin.username=admin
voiceout.admin.password=admin123
voiceout.submission-limit.max-per-window=5
voiceout.submission-limit.window-minutes=10